backend:
  name: github
  repo: syntaxerror019/miles
  branch: main
  auth_methods: [token]

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    summary: "{{title}} — {{date}}"
    format: "yaml-frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZZ" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Cover Image", name: "image", widget: "image", required: false }
      - { label: "Draft (hide from site)", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }